In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (2.5.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (2.5.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\ProgramData\anaconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\ProgramData\anaconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\ProgramData\anaconda3\Lib\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\ProgramData\anaconda3\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\ProgramData\anaconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\AKASH\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\ProgramData\anaconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\ProgramData\anaconda3\Lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv(r"C:\Users\AKASH\OneDrive\Desktop\Data\NCRB_Table_1A.1.csv")

In [11]:
display(data)

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
0,1,Andhra Pradesh,188997,179611,158547,530.3,299.0,86.5
1,2,Arunachal Pradesh,2244,2626,2308,15.5,148.8,47.2
2,3,Assam,111558,119883,59315,354.9,167.1,32.6
3,4,Bihar,194698,186006,211079,1255.3,168.1,75.4
4,5,Chhattisgarh,65216,70519,73822,299.5,246.5,80.4
5,6,Goa,3393,2099,2711,15.7,172.8,75.9
6,7,Gujarat,381849,273056,134600,709.3,189.8,89.8
7,8,Haryana,103276,112720,125435,299.7,418.6,43.3
8,9,Himachal Pradesh,14803,13041,13231,74.4,177.8,82.9
9,10,Jharkhand,51033,47684,48726,391.4,124.5,58.2
10,11,Karnataka,106350,115728,129461,674.1,192.1,78.3
11,12,Kerala,149099,142643,235858,356.8,661.0,96.0
12,13,Madhya Pradesh,283881,304066,298578,858.9,347.6,86.6
13,14,Maharashtra,394017,367218,374038,1257.4,297.5,75.3
14,15,Manipur,2349,2484,3029,32.0,94.6,10.4
15,16,Meghalaya,2871,2672,2914,33.3,87.6,26.9
16,17,Mizoram,1787,2467,3587,12.3,291.6,58.0
17,18,Nagaland,1022,1033,1008,22.2,45.4,58.0
18,19,Odisha,108533,124956,143414,460.8,311.2,77.9
19,20,Punjab,49870,46454,43738,306.0,142.9,66.4
20,21,Rajasthan,193279,214552,236090,804.4,293.5,49.8
21,22,Sikkim,504,532,549,6.8,80.3,55.5
22,23,Tamil Nadu,891700,322852,193913,767.1,252.8,70.7
23,24,Telangana,135885,146131,151849,379.5,400.1,79.1
24,25,Tripura,4010,4133,3653,41.2,88.7,73.1
25,26,Uttar Pradesh,355110,357905,401787,2340.9,171.6,76.1
26,27,Uttarakhand,13812,15704,16967,115.6,146.8,71.5
27,28,West Bengal,158060,157498,156503,987.6,158.5,90.6
28,Total State (S),Total State (S),3969206,3336273,3226710,13403.0,240.7,74.9
29,29,Andaman and Nicobar Islands,482,386,460,4.0,114.4,83.9
30,30,Chandigarh,2583,2401,2941,12.2,240.5,54.4
31,31,Dadra and Nagar Haveli and Daman and Diu,441,490,1184,12.0,98.6,82.5
32,32,Delhi,249192,291904,300429,211.0,1424.1,30.2
33,33,Jammu and Kashmir,25233,27447,25915,135.4,191.4,77.1
34,34,Ladakh,387,519,439,3.0,146.8,82.4
35,35,Lakshadweep,107,89,64,0.7,92.8,73.5
36,36,Puducherry,6725,3851,3237,16.2,199.7,91.3
37,Total UT(S),Total UT(S),285150,327087,334669,394.5,848.4,35.6
38,Total All India,Total All India,4254356,3663360,3561379,13797.5,258.1,71.3

In [12]:
data.head()

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
0,1,Andhra Pradesh,188997,179611,158547,530.3,299.0,86.5
1,2,Arunachal Pradesh,2244,2626,2308,15.5,148.8,47.2
2,3,Assam,111558,119883,59315,354.9,167.1,32.6
3,4,Bihar,194698,186006,211079,1255.3,168.1,75.4
4,5,Chhattisgarh,65216,70519,73822,299.5,246.5,80.4

In [13]:
data.shape

(39, 8)

In [14]:
data.columns

Index(['Sl. No.', 'State/UT', '2020', '2021', '2022',
       'Mid-Year Projected Population (in Lakhs) (2022)',
       'Rate of Cognizable Crimes (IPC) (2022)', 'Chargesheeting Rate (2022)'],
      dtype='str')

In [15]:
data.dtypes

Sl. No.                                                str
State/UT                                               str
2020                                                 int64
2021                                                 int64
2022                                                 int64
Mid-Year Projected Population (in Lakhs) (2022)    float64
Rate of Cognizable Crimes (IPC) (2022)             float64
Chargesheeting Rate (2022)                         float64
dtype: object

In [16]:
data.isnull().sum()

Sl. No.                                            0
State/UT                                           0
2020                                               0
2021                                               0
2022                                               0
Mid-Year Projected Population (in Lakhs) (2022)    0
Rate of Cognizable Crimes (IPC) (2022)             0
Chargesheeting Rate (2022)                         0
dtype: int64

In [17]:
data.duplicated().sum()

np.int64(0)

In [18]:
data["State/UT"].unique()

<ArrowStringArray>
[                          'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                             'Chhattisgarh',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal',
                          'Total State (S)',
              'Andaman and Nicobar Islands',
                               'Chandigarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                        'Jammu and Kashmir',
                                   'Ladakh',
                              'Lakshadweep',
                               'Puducherry',
                              'Total UT(S)',
                          'Total All India']
Length: 39, dtype: str

In [19]:
total_rows = [
    "Total State (S)",
    "Total UT(S)",
    "Total All India"
]
data_clean = data[~data["State/UT"].isin(total_rows)].copy()

In [20]:
data_clean.shape

(36, 8)

In [21]:
crime_columns = ["2020", "2021", "2022"]

for col in crime_columns:
    data_clean[col] = pd.to_numeric(
        data_clean[col],
        errors="coerce"
    )

In [22]:
data_clean["Crime Change 2020-2022"] = (
    data_clean["2022"] - data_clean["2020"]
)

In [23]:
data_clean["Crime Change % 2020-2022"] = (
    (data_clean["2022"] - data_clean["2020"])
    / data_clean["2020"]
) * 100

In [24]:
data_clean["Crime Change % 2020-2022"] = (
    data_clean["Crime Change % 2020-2022"].round(2)
)

In [25]:
data_clean = data_clean.rename(columns={
    "Sl. No.": "Serial_No",
    "State/UT": "State_UT",
    "Mid-Year Projected Population (in Lakhs) (2022)": "Population_Lakhs",
    "Rate of Cognizable Crimes (IPC) (2022)": "Crime_Rate_2022",
    "Chargesheeting Rate (2022)": "Chargesheeting_Rate_2022"
})

In [26]:
data_clean.columns

Index(['Serial_No', 'State_UT', '2020', '2021', '2022', 'Population_Lakhs',
       'Crime_Rate_2022', 'Chargesheeting_Rate_2022', 'Crime Change 2020-2022',
       'Crime Change % 2020-2022'],
      dtype='str')

In [27]:
data_clean.describe()

,2020,2021,2022,Population_Lakhs,Crime_Rate_2022,Chargesheeting_Rate_2022,Crime Change 2020-2022,Crime Change % 2020-2022
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,118176.555556,101760.000000,98927.194444,383.261111,241.252778,67.991667,-19249.361111,6.271111
std,176923.509449,118652.699382,117142.926576,497.400312,235.523156,20.334367,126044.146597,42.656383
min,107.000000,89.000000,64.000000,0.700000,45.400000,10.400000,-697787.000000,-78.250000
25%,2524.500000,2479.750000,2934.250000,16.075000,138.300000,57.375000,-1560.750000,-9.330000
50%,50451.500000,47069.000000,46232.000000,255.250000,175.300000,75.350000,58.000000,4.015000
75%,165794.250000,163026.250000,157014.000000,566.250000,292.075000,82.425000,15013.750000,20.785000
max,891700.000000,367218.000000,401787.000000,2340.900000,1424.100000,96.000000,86759.000000,168.480000

In [28]:
data_clean.loc[
    data_clean["2022"].idxmax()
]

Serial_No                              26
State_UT                    Uttar Pradesh
2020                               355110
2021                               357905
2022                               401787
Population_Lakhs                   2340.9
Crime_Rate_2022                     171.6
Chargesheeting_Rate_2022             76.1
Crime Change 2020-2022              46677
Crime Change % 2020-2022            13.14
Name: 25, dtype: object

In [29]:
data_clean.loc[
    data_clean["Crime_Rate_2022"].idxmax()
]

Serial_No                       32
State_UT                     Delhi
2020                        249192
2021                        291904
2022                        300429
Population_Lakhs             211.0
Crime_Rate_2022             1424.1
Chargesheeting_Rate_2022      30.2
Crime Change 2020-2022       51237
Crime Change % 2020-2022     20.56
Name: 32, dtype: object

In [30]:
data_clean.nlargest(
    10,
    "2022"
)[["State_UT", "2022"]]

          State_UT    2022
25   Uttar Pradesh  401787
13     Maharashtra  374038
32           Delhi  300429
12  Madhya Pradesh  298578
20       Rajasthan  236090
11          Kerala  235858
3            Bihar  211079
22      Tamil Nadu  193913
0   Andhra Pradesh  158547
27     West Bengal  156503

In [31]:
columnName = '2020'
columnName = '2021'
columnName = '2022'

Q1 = data[columnName].quantile(0.25)
Q3 = data[columnName].quantile(0.75)

print("Q1:", Q1)
print("Q3:", Q3)

IQR = Q3 - Q1
print("IQR:", IQR)

LB = Q1 - 1.5 * IQR
print("Lower Bound:", LB)

UB = Q3 + 1.5 * IQR
print("Upper Bound:", UB)

outliers = data[
    (data[columnName] < LB) |
    (data[columnName] > UB)
]

print(f"No. of Outliers: {len(outliers)}")

display(outliers)

Q1: 2985.0
Q3: 202496.0
IQR: 199511.0
Lower Bound: -296281.5
Upper Bound: 501762.5
No. of Outliers: 2

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
28,Total State (S),Total State (S),3969206,3336273,3226710,13403.0,240.7,74.9
38,Total All India,Total All India,4254356,3663360,3561379,13797.5,258.1,71.3

In [32]:
data_clean.nlargest(
    10,
    "Chargesheeting_Rate_2022"
)[["State_UT", "Chargesheeting_Rate_2022"]]

                                    State_UT  Chargesheeting_Rate_2022
11                                    Kerala                      96.0
36                                Puducherry                      91.3
27                               West Bengal                      90.6
6                                    Gujarat                      89.8
12                            Madhya Pradesh                      86.6
0                             Andhra Pradesh                      86.5
29               Andaman and Nicobar Islands                      83.9
8                           Himachal Pradesh                      82.9
31  Dadra and Nagar Haveli and Daman and Diu                      82.5
34                                    Ladakh                      82.4

In [33]:
data_clean.info()

<class 'pandas.DataFrame'>
Index: 36 entries, 0 to 36
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Serial_No                 36 non-null     str
 1   State_UT                  36 non-null     str
 2   2020                      36 non-null     int64
 3   2021                      36 non-null     int64
 4   2022                      36 non-null     int64
 5   Population_Lakhs          36 non-null     float64
 6   Crime_Rate_2022           36 non-null     float64
 7   Chargesheeting_Rate_2022  36 non-null     float64
 8   Crime Change 2020-2022    36 non-null     int64
 9   Crime Change % 2020-2022  36 non-null     float64
dtypes: float64(4), int64(4), str(2)
memory usage: 4.6 KB

In [34]:
data_clean.head()

,Serial_No,State_UT,2020,2021,2022,Population_Lakhs,Crime_Rate_2022,Chargesheeting_Rate_2022,Crime Change 2020-2022,Crime Change % 2020-2022
0,1,Andhra Pradesh,188997,179611,158547,530.3,299.0,86.5,-30450,-16.11
1,2,Arunachal Pradesh,2244,2626,2308,15.5,148.8,47.2,64,2.85
2,3,Assam,111558,119883,59315,354.9,167.1,32.6,-52243,-46.83
3,4,Bihar,194698,186006,211079,1255.3,168.1,75.4,16381,8.41
4,5,Chhattisgarh,65216,70519,73822,299.5,246.5,80.4,8606,13.20

In [35]:
data_clean.to_csv(
    "cleaned_india_crime_data.csv",
    index=False
)

In [36]:
import os

print(os.getcwd())

C:\Users\AKASH\Documents\ADST\project

In [37]:
data = data.rename(columns={
    "2020": "Crime_2020",
    "2021": "Crime_2021",
    "2022": "Crime_2022",
    "Crime_Rate_2022": "Crime_Rate",
    "Chargesheeting_Rate_2022": "Chargesheeting_Rate",
    "Crime Change 2020-2022": "Crime_Change",
    "Crime Change % 2020-2022": "Crime_Change_Percent"
})

In [38]:
print(data.columns.tolist())

['Sl. No.', 'State/UT', 'Crime_2020', 'Crime_2021', 'Crime_2022', 'Mid-Year Projected Population (in Lakhs) (2022)', 'Rate of Cognizable Crimes (IPC) (2022)', 'Chargesheeting Rate (2022)']

In [42]:
data.to_csv(
    "final_crime_data.csv",
    index=False
)

print("File saved successfully!")

File saved successfully!

In [43]:
columnName = "Crime_2022"

Q1 = data[columnName].quantile(0.25)
Q3 = data[columnName].quantile(0.75)

print("Q1:", Q1)
print("Q3:", Q3)

IQR = Q3 - Q1

print("IQR:", IQR)

LB = Q1 - 1.5 * IQR
UB = Q3 + 1.5 * IQR

print("Lower Bound:", LB)
print("Upper Bound:", UB)

outliers = data[
    (data[columnName] < LB) |
    (data[columnName] > UB)
]

print(f"No. of Outliers: {len(outliers)}")

display(outliers)

Q1: 2985.0
Q3: 202496.0
IQR: 199511.0
Lower Bound: -296281.5
Upper Bound: 501762.5
No. of Outliers: 2

,Sl. No.,State/UT,Crime_2020,Crime_2021,Crime_2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Cognizable Crimes (IPC) (2022),Chargesheeting Rate (2022)
28,Total State (S),Total State (S),3969206,3336273,3226710,13403.0,240.7,74.9
38,Total All India,Total All India,4254356,3663360,3561379,13797.5,258.1,71.3

In [44]:
import os

print(os.getcwd())

C:\Users\AKASH\Documents\ADST\project